// Pixel matrices for obstacles and pickups. Char map in palette.js.
// R red, X dark red, Y amber, D black(taxi), G grey, S slate, Z dark slate,
// O stone, W wet, M moss, C cream, K ink, B ball, T tan.

export const CONE = [ // 13 x 17 -> 26x34
  '......Y......',
  '.....RRR.....',
  '.....RRR.....',
  '....RRRRR....',
  '....RRRRR....',
  '....CCCCC....',
  '...CCCCCCC...',
  '...RRRRRRR...',
  '...RRRRRRR...',
  '..RRRRRRRRR..',
  '..CCCCCCCCC..',
  '..RRRRRRRRR..',
  '.RRRRRRRRRRR.',
  '.RRRRRRRRRRR.',
  '.RRRRRRRRRRR.',
  'XXXXXXXXXXXXX',
  'XXXXXXXXXXXXX',
];

export const PHONEBOX = [ // 22 x 38 -> 44x76
  '......RRRRRRRRRR......',
  '....RRRRRRRRRRRRRR....',
  '..RRRRRRRRRRRRRRRRRR..',
  '.RRRRRRRRRRRRRRRRRRRR.',
  '.RRRCCCCCCCCCCCCCCRRR.',
  '.RRRCCCCCCCCCCCCCCRRR.',
  '.RRRRRRRRRRRRRRRRRRRR.',
  '.RRRRRRRRRRRRRRRRRRRR.',
  '.RRWWWWRRWWWWRRWWWWRR.',
  '.RRWWWWRRWWWWRRWWWWRR.',
  '.RRWWWWRRWWWWRRWWWWRR.',
  '.RRRRRRRRRRRRRRRRRRRR.',
  '.RRWWWWRRWWWWRRWWWWRR.',
  '.RRWWWWRRWWWWRRWWWWRR.',
  '.RRWWWWRRWWWWRRWWWWRR.',
  '.RRRRRRRRRRRRRRRRRRRR.',
  '.RRWWWWRRWWWWRRWWWWRR.',
  '.RRWWWWRRWWWWRRWWWWRR.',
  '.RRWWWWRRWWWWRRWWWWRR.',
  '.RRRRRRRRRRRRRRRRRRRR.',
  '.RRWWWWRRWWWWRRWWWWRR.',
  '.RRWWWWRRWWWWRRWWWWRR.',
  '.RRWWWWRRWWWWRRWWWWRR.',
  '.RRRRRRRRRRRRRRRRRRRR.',
  '.RRWWWWRRWWWWRRWWWWRR.',
  '.RRWWWWRRWWWWRRWWWWRR.',
  '.RRWWWWRRWWWWRRWWWWRR.',
  '.RRRRRRRRRRRRRRRRRRRR.',
  '.RRRRRRRRRRRRRRRRRRRR.',
  '.RXXRRRRRRRRRRRRRRXXR.',
  '.RXXRRRRRRRRRRRRRRXXR.',
  '.RXXRRRRRRRRRRRRRRXXR.',
  '.RXXRRRRRRRRRRRRRRXXR.',
  '.RXXRRRRRRRRRRRRRRXXR.',
  '.RXXRRRRRRRRRRRRRRXXR.',
  '.RRRRRRRRRRRRRRRRRRRR.',
  'XXXXXXXXXXXXXXXXXXXXXX',
  'XXXXXXXXXXXXXXXXXXXXXX',
];

export const BIN = [ // 19 x 23 -> 38x46
  '...ZZZZZZZZZZZZZ...',
  '..ZZZZZZZZZZZZZZZ..',
  '.ZGGGGGGGGGGGGGGGZ.',
  '.ZZZZZZZZZZZZZZZZZ.',
  '..ZGGGGGGGGGGGGGZ..',
  '..ZGGGGGGGGGGGGGZ..',
  '..ZGGGGGGGGGGGGGZ..',
  '..ZGGGZZZZZZZGGGZ..',
  '..ZGGGZZZZZZZGGGZ..',
  '..ZGGGGGGGGGGGGGZ..',
  '..ZGGGGGGGGGGGGGZ..',
  '..ZGGGGGGGGGGGGGZ..',
  '..ZGGGGGGGGGGGGGZ..',
  '..ZGGGGGGGGGGGGGZ..',
  '..ZGGGGGGGGGGGGGZ..',
  '..ZGGGGGGGGGGGGGZ..',
  '..ZGGGGGGGGGGGGGZ..',
  '..ZGGGGGGGGGGGGGZ..',
  '..ZGGGGGGGGGGGGGZ..',
  '..ZZZZZZZZZZZZZZZ..',
  '..ZZZ..........ZZZ.',
  '..ZZZ..........ZZZ.',
  '..ZZZ..........ZZZ.',
];

export const PIGEON_1 = [ // 11 x 9 -> 22x18
  '....SS.....',
  '...SSSS....',
  '..SSSSSSS..',
  'SSSSSSSSSSK',
  '.SSSSSSSSS.',
  '..WWWSSSS..',
  '...WWWSS...',
  '.....W.....',
  '...........',
];

export const PIGEON_2 = [
  '...........',
  '...........',
  '....SS.....',
  '...SSSS...K',
  '..SSSSSSSK.',
  'SSSSSSSSSS.',
  '.WWWWSSSS..',
  '..WWWSS....',
  '....W......',
];

export const CAB = [ // 48 x 26 -> 96x52
  '..............DDDDDDDDDDDDDDDDDD...............',
  '...........DDDDDDDDDDDDDDDDDDDDDDD.............',
  '..........DDWWWWWWDDDDDDWWWWWWWWDDD............',
  '.........DDWWWWWWWWDDDDWWWWWWWWWWDDD...........',
  '........DDWWWWWWWWWWDDWWWWWWWWWWWWDDD..........',
  '.......DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.........',
  '....DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD....',
  '..DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD..',
  '.DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.',
  '.DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.',
  '.DDYYDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.',
  '.DDYYDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.',
  '.DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.',
  '.DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.',
  '.DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD.',
  '..DDDDDDZZZZDDDDDDDDDDDDDDDDDDDDDDZZZZDDDDDD..',
  '....DDDZZZZZZDDDDDDDDDDDDDDDDDDDDZZZZZZDDD....',
  '.......ZZKKZZ....................ZZKKZZ........',
  '.......ZKKKKZ....................ZKKKKZ........',
  '.......ZKKKKZ....................ZKKKKZ........',
  '.......ZZKKZZ....................ZZKKZZ........',
  '........ZZZZ......................ZZZZ.........',
  '...............................................',
  '...............................................',
  '...............................................',
  '...............................................',
];

export const SQUIRREL_1 = [ // 12 x 11 -> 24x22
  '........TTT.',
  '.......TTTTT',
  '.......TTTTT',
  'TT.....TTKTT',
  'TTT...TTTTT.',
  'TTTT.TTTTTT.',
  '.TTTTTTTTT..',
  '.TTTTTTTT...',
  '..TTTTTTT...',
  '...TT..TT...',
  '...T....T...',
];

export const SQUIRREL_2 = [
  '........TTT.',
  '.......TTTTT',
  '..TT...TTTTT',
  '.TTTT..TTKTT',
  '.TTTT.TTTTT.',
  '.TTTTTTTTTT.',
  '..TTTTTTTT..',
  '..TTTTTTTT..',
  '..TTTTTTT...',
  '..TT....TT..',
  '.T........T.',
];

export const BUS = [ // 75 x 44 -> 150x88
  '....RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR....',
  '..RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR..',
  '.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.',
  '.RRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCRRR.',
  '.RRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWCRRR.',
  '.RRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWCRRR.',
  '.RRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCRRR.',
  '.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.',
  '.RRCCCCCCCCCCCCCCCCCCCCCCCCCCCCRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.',
  '.RRCCCCCCCCCCCCCCCCCCCCCCCCCCCCRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.',
  '.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.',
  '.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.',
  '.RRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCRRR.',
  '.RRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWCRRR.',
  '.RRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWCRRR.',
  '.RRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWWWCRRCWWCRRR.',
  '.RRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCCCRRCCCCRRR.',
  '.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.',
  '.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.',
  '.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.',
  '.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.',
  '.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.',
  '...ZZZZZZ..............ZZZZZZ..................ZZZZZZ..............ZZZZ....',
  '..ZZZKKZZZ............ZZZKKZZZ................ZZZKKZZZ............ZZKKZZ...',
  '..ZZKKKKZZ............ZZKKKKZZ................ZZKKKKZZ............ZKKKKZ...',
  '..ZZKKKKZZ............ZZKKKKZZ................ZZKKKKZZ............ZKKKKZ...',
  '..ZZZKKZZZ............ZZZKKZZZ................ZZZKKZZZ............ZZKKZZ...',
  '...ZZZZZZ..............ZZZZZZ..................ZZZZZZ..............ZZZZ....',
  // Overhang: rows below are empty — the duck-under gap is drawn by placing
  // the bus sprite high; collision uses the overhang box only.
  '............................................................................',
  '............................................................................',
  '............................................................................',
  '............................................................................',
  '............................................................................',
  '............................................................................',
  '............................................................................',
  '............................................................................',
  '............................................................................',
  '............................................................................',
  '............................................................................',
  '............................................................................',
  '............................................................................',
  '............................................................................',
  '............................................................................',
  '............................................................................',
];

export const BONE = [ // 9 x 6 -> 18x12
  'CC.....CC',
  'CCCCCCCCC',
  '.CCCCCCC.',
  '.CCCCCCC.',
  'CCCCCCCCC',
  'CC.....CC',
];

export const HEART = [ // 8 x 7 -> 16x14
  '.PP..PP.',
  'PPPPPPPP',
  'PPPPPPPP',
  'PPPPPPPP',
  '.PPPPPP.',
  '..PPPP..',
  '...PP...',
];
